// Banco de profissões detalhado — centenas de carreiras organizadas por área
export const CAREER_DATABASE = [
  // ===== EXATAS =====
  { title: "Engenharia Civil", area: "Exatas", subarea: "Engenharia", description: "Planeja, projeta e supervisiona obras de construção civil, desde edifícios a pontes e rodovias.", average_salary: "R$ 8.000", salary_range: "R$ 4.000 - R$ 18.000", education_time: "5 anos", education_level: "Superior", skills: ["Matemática", "Física", "Desenho Técnico", "Gestão de Projetos", "Geometria Analítica"], market: "Mercado aquecido na construção civil e infraestrutura", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Trabalho entre escritório (projetos) e campo (obras)" },
  { title: "Engenharia de Software", area: "Exatas", subarea: "Tecnologia", description: "Desenvolve, testa e mantém sistemas e aplicações de software.", average_salary: "R$ 10.000", salary_range: "R$ 5.000 - R$ 25.000", education_time: "5 anos", education_level: "Superior", skills: ["Lógica de Programação", "Algoritmos", "Banco de Dados", "Git", "Arquitetura de Software"], market: "Altíssima demanda globalmente", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Trabalho remoto ou escritório, desenvolvimento de código e reuniões" },
  { title: "Engenharia Mecânica", area: "Exatas", subarea: "Engenharia", description: "Projeta, constrói e mantém máquinas, motores e sistemas mecânicos.", average_salary: "R$ 7.500", salary_range: "R$ 4.000 - R$ 15.000", education_time: "5 anos", education_level: "Superior", skills: ["Física", "Desenho Técnico", "Mecânica", "Termodinâmica", "CAD"], market: "Demanda em indústria e automotivo", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Escritório técnico e chão de fábrica" },
  { title: "Matemática", area: "Exatas", subarea: "Ciências Exatas", description: "Estuda números, estruturas e padrões, aplicando em pesquisa, finanças e tecnologia.", average_salary: "R$ 6.000", salary_range: "R$ 3.500 - R$ 14.000", education_time: "4 anos", education_level: "Superior", skills: ["Cálculo", "Álgebra Linear", "Lógica", "Estatística", "Análise"], market: "Oportunidades em pesquisa, dados e ensino", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Pesquisa, análise de dados e docência" },
  { title: "Física", area: "Exatas", subarea: "Ciências Exatas", description: "Investiga as leis da natureza, da mecânica à física quântica.", average_salary: "R$ 6.500", salary_range: "R$ 3.500 - R$ 15.000", education_time: "4 anos", education_level: "Superior", skills: ["Cálculo", "Mecânica", "Termodinâmica", "Óptica", "Programação Científica"], market: "Pesquisa, tecnologia e ensino", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Laboratório, pesquisa e docência" },
  { title: "Estatística", area: "Exatas", subarea: "Ciências Exatas", description: "Coleta, analisa e interpreta dados para tomada de decisão.", average_salary: "R$ 7.000", salary_range: "R$ 4.000 - R$ 16.000", education_time: "4 anos", education_level: "Superior", skills: ["Probabilidade", "R/Python", "Análise de Dados", "Modelagem", "Inferência"], market: "Alta demanda em dados e mercado financeiro", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Análise de dados e relatórios" },
  { title: "Economia", area: "Exatas", subarea: "Ciências Sociais Aplicadas", description: "Estuda produção, distribuição e consumo de bens e serviços.", average_salary: "R$ 8.500", salary_range: "R$ 4.500 - R$ 20.000", education_time: "4 anos", education_level: "Superior", skills: ["Macroeconomia", "Microeconomia", "Econometria", "Estatística", "Análise"], market: "Bancos, consultorias e governo", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Análise de mercado, relatórios e reuniões" },
  { title: "Contabilidade", area: "Exatas", subarea: "Ciências Contábeis", description: "Registra e controla patrimônio e finanças de empresas e pessoas.", average_salary: "R$ 4.500", salary_range: "R$ 2.500 - R$ 12.000", education_time: "4 anos", education_level: "Superior", skills: ["Contabilidade", "Tributos", "Excel", "Auditoria", "Finanças"], market: "Demanda constante em todas as empresas", growth_trend: "Estável", entry_difficulty: "Baixa", remote_possible: true, international_possible: true, routine: "Escritório, análises financeiras e relatórios" },
  { title: "Engenharia Elétrica", area: "Exatas", subarea: "Engenharia", description: "Projeta sistemas elétricos, de energia e eletrônicos.", average_salary: "R$ 8.000", salary_range: "R$ 4.500 - R$ 18.000", education_time: "5 anos", education_level: "Superior", skills: ["Eletrotécnica", "Circuitos", "Física", "Automação", "Projetos Elétricos"], market: "Energia, telecomunicações e automação", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Projetos em escritório e campo" },
  { title: "Engenharia Química", area: "Exatas", subarea: "Engenharia", description: "Desenvolve processos químicos e materiais para indústria.", average_salary: "R$ 8.500", salary_range: "R$ 5.000 - R$ 18.000", education_time: "5 anos", education_level: "Superior", skills: ["Química", "Termodinâmica", "Processos Industriais", "Segurança", "Análise"], market: "Petróleo, farmacêutica e alimentos", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Laboratório e planta industrial" },

  // ===== HUMANAS =====
  { title: "Psicologia", area: "Humanas", subarea: "Saúde Mental", description: "Estuda o comportamento humano e oferece terapia e orientação.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 12.000", education_time: "5 anos", education_level: "Superior", skills: ["Empatia", "Comunicação", "Escuta Ativa", "Ética", "Análise Comportamental"], market: "Crescente com saúde mental em alta", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: false, routine: "Consultas, escuta e relatórios clínicos" },
  { title: "Pedagogia", area: "Humanas", subarea: "Educação", description: "Forma educadores e gestores de processos de ensino-aprendizagem.", average_salary: "R$ 3.000", salary_range: "R$ 2.000 - R$ 8.000", education_time: "4 anos", education_level: "Superior", skills: ["Didática", "Comunicação", "Paciência", "Planejamento", "Avaliação"], market: "Demanda constante em escolas e empresas", growth_trend: "Estável", entry_difficulty: "Baixa", remote_possible: true, international_possible: true, routine: "Sala de aula e planejamento pedagógico" },
  { title: "Direito", area: "Humanas", subarea: "Jurídico", description: "Atua na interpretação e aplicação das leis, defendendo direitos.", average_salary: "R$ 8.000", salary_range: "R$ 4.000 - R$ 30.000", education_time: "5 anos", education_level: "Superior", skills: ["Argumentação", "Leitura", "Escrita", "Lógica Jurídica", "Oratória"], market: "Amplas oportunidades em escritórios e empresas", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Análise de processos, audiências e consultoria" },
  { title: "Jornalismo", area: "Humanas", subarea: "Comunicação", description: "Apura, redige e veicula notícias e informações.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 12.000", education_time: "4 anos", education_level: "Superior", skills: ["Escrita", "Comunicação", "Curiosidade", "Edição", "Mídias Digitais"], market: "Transformação digital e conteúdo", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Pautas, entrevistas e produção de conteúdo" },
  { title: "Sociologia", area: "Humanas", subarea: "Ciências Sociais", description: "Estuda a sociedade, grupos e fenômenos sociais.", average_salary: "R$ 5.000", salary_range: "R$ 3.000 - R$ 12.000", education_time: "4 anos", education_level: "Superior", skills: ["Análise Social", "Pesquisa", "Escrita", "Estatística", "Pensamento Crítico"], market: "Pesquisa, ONGs e políticas públicas", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Pesquisa de campo e análise" },
  { title: "História", area: "Humanas", subarea: "Ciências Humanas", description: "Estuda o passado humano e suas implicações no presente.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Pesquisa", "Escrita", "Análise de Fontes", "Curiosidade", "Pensamento Crítico"], market: "Ensino, pesquisa e patrimônio", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Pesquisa, docência e curadoria" },
  { title: "Geografia", area: "Humanas", subarea: "Ciências Humanas", description: "Estuda o espaço, o meio ambiente e as relações territoriais.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Cartografia", "Geoprocessamento", "Análise Ambiental", "Pesquisa", "GIS"], market: "Meio ambiente, urbanismo e ensino", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Trabalho de campo e análise espacial" },
  { title: "Filosofia", area: "Humanas", subarea: "Ciências Humanas", description: "Reflete sobre existência, conhecimento e ética.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Pensamento Crítico", "Leitura", "Argumentação", "Escrita", "Lógica"], market: "Ensino, pesquisa e ética aplicada", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Estudo, escrita e docência" },
  { title: "Relações Internacionais", area: "Humanas", subarea: "Ciências Sociais", description: "Analisa relações entre países, diplomacia e comércio global.", average_salary: "R$ 7.000", salary_range: "R$ 4.000 - R$ 18.000", education_time: "4 anos", education_level: "Superior", skills: ["Diplomacia", "Idiomas", "Análise Política", "Negociação", "Cultura"], market: "Embaixadas, empresas e ONGs", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Análise geopolítica e negociação" },
  { title: "Serviço Social", area: "Humanas", subarea: "Assistência", description: "Promove direitos sociais e assistência a comunidades vulneráveis.", average_salary: "R$ 3.500", salary_range: "R$ 2.000 - R$ 8.000", education_time: "4 anos", education_level: "Superior", skills: ["Empatia", "Comunicação", "Gestão Social", "Ética", "Visão Sistêmica"], market: "Demanda em saúde, educação e assistência", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Atendimento e visitas domiciliares" },

  // ===== BIOLÓGICAS =====
  { title: "Medicina", area: "Biológicas", subarea: "Saúde", description: "Diagnostica e trata doenças, cuidando da saúde das pessoas.", average_salary: "R$ 12.000", salary_range: "R$ 6.000 - R$ 40.000", education_time: "6 anos", education_level: "Superior", skills: ["Conhecimento Clínico", "Empatia", "Lógica", "Prática", "Resiliência"], market: "Demanda altíssima e contínua", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Consultas, plantões e procedimentos" },
  { title: "Enfermagem", area: "Biológicas", subarea: "Saúde", description: "Cuida de pacientes, aplica tratamentos e apoia a equipe médica.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 10.000", education_time: "5 anos", education_level: "Superior", skills: ["Cuidados Clínicos", "Empatia", "Organização", "Prática", "Resistência"], market: "Demanda altíssima em hospitais", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Plantões e cuidados diretos" },
  { title: "Biomedicina", area: "Biológicas", subarea: "Saúde", description: "Realiza exames laboratoriais e pesquisa em saúde.", average_salary: "R$ 4.500", salary_range: "R$ 2.500 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Análise Clínica", "Laboratório", "Pesquisa", "Precisão", "Ética"], market: "Laboratórios e pesquisa", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Laboratório e análise de amostras" },
  { title: "Farmácia", area: "Biológicas", subarea: "Saúde", description: "Dispensa medicamentos e orienta sobre seu uso.", average_salary: "R$ 4.500", salary_range: "R$ 2.500 - R$ 12.000", education_time: "5 anos", education_level: "Superior", skills: ["Farmacologia", "Química", "Atendimento", "Ética", "Gestão"], market: "Farmácias, indústria e hospitais", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Dispensação e orientação farmacêutica" },
  { title: "Medicina Veterinária", area: "Biológicas", subarea: "Saúde Animal", description: "Cuida da saúde de animais domésticos e de produção.", average_salary: "R$ 5.000", salary_range: "R$ 3.000 - R$ 15.000", education_time: "5 anos", education_level: "Superior", skills: ["Anatomia Animal", "Empatia", "Clínica", "Prática", "Resiliência"], market: "Pet em alta e agronegócio", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Consultas e cirurgias em animais" },
  { title: "Odontologia", area: "Biológicas", subarea: "Saúde", description: "Cuida da saúde bucal dos pacientes.", average_salary: "R$ 5.500", salary_range: "R$ 3.000 - R$ 20.000", education_time: "5 anos", education_level: "Superior", skills: ["Anatomia", "Prática Manual", "Empatia", "Precisão", "Gestão"], market: "Demanda constante, alta oportunidade de clínica própria", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Consultas e procedimentos odontológicos" },
  { title: "Nutrição", area: "Biológicas", subarea: "Saúde", description: "Orienta alimentação saudável e dietas personalizadas.", average_salary: "R$ 3.500", salary_range: "R$ 2.000 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Bioquímica", "Comunicação", "Empatia", "Planejamento", "Saúde"], market: "Crescente com saúde preventiva", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Consultas e planos alimentares" },
  { title: "Fisioterapia", area: "Biológicas", subarea: "Saúde", description: "Reabilita movimento e função corporal.", average_salary: "R$ 4.000", salary_range: "R$ 2.500 - R$ 12.000", education_time: "5 anos", education_level: "Superior", skills: ["Anatomia", "Cinesiologia", "Empatia", "Prática Manual", "Resiliência"], market: "Reabilitação e bem-estar em alta", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Sessões e acompanhamento de pacientes" },
  { title: "Biologia", area: "Biológicas", subarea: "Ciências da Vida", description: "Estuda os seres vivos e seus ecossistemas.", average_salary: "R$ 4.500", salary_range: "R$ 2.500 - R$ 12.000", education_time: "4 anos", education_level: "Superior", skills: ["Pesquisa", "Genética", "Ecologia", "Laboratório", "Curiosidade"], market: "Pesquisa, meio ambiente e biotecnologia", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Laboratório e trabalho de campo" },
  { title: "Agronomia", area: "Biológicas", subarea: "Agropecuária", description: "Gestiona produção agrícola e recursos naturais.", average_salary: "R$ 7.000", salary_range: "R$ 4.000 - R$ 18.000", education_time: "5 anos", education_level: "Superior", skills: ["Solos", "Fitotecnia", "Gestão", "Tecnologia", "Análise"], market: "Agronegócio é potência do Brasil", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Trabalho de campo e gestão agrícola" },

  // ===== ARTES =====
  { title: "Design Gráfico", area: "Artes", subarea: "Design Visual", description: "Cria identidades visuais, materiais e peças digitais.", average_salary: "R$ 3.500", salary_range: "R$ 2.000 - R$ 12.000", education_time: "3-4 anos", education_level: "Tecnólogo", skills: ["Criatividade", "Photoshop", "Ilustrator", "Tipografia", "Composição"], market: "Demanda em agências e freelancer", growth_trend: "Crescente", entry_difficulty: "Baixa", remote_possible: true, international_possible: true, routine: "Criação digital e reuniões de briefing" },
  { title: "Arquitetura e Urbanismo", area: "Artes", subarea: "Projeto", description: "Projeta edifícios e espaços urbanos funcionais e estéticos.", average_salary: "R$ 7.000", salary_range: "R$ 4.000 - R$ 20.000", education_time: "5 anos", education_level: "Superior", skills: ["Desenho Técnico", "Criatividade", "CAD", "Maquetaria", "Visão Espacial"], market: "Construção e urbanismo", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Projetos em escritório e visitas" },
  { title: "Artes Visuais", area: "Artes", subarea: "Arte Plástica", description: "Expressa ideias por pintura, escultura e instalações.", average_salary: "R$ 3.000", salary_range: "R$ 1.500 - R$ 15.000", education_time: "4 anos", education_level: "Superior", skills: ["Criatividade", "Técnica Pictórica", "Sensibilidade", "Curiosidade", "Expressão"], market: "Galerias, ensino e projetos", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Atelier e exposições" },
  { title: "Fotografia", area: "Artes", subarea: "Imagem", description: "Registra momentos e produtos por imagem.", average_salary: "R$ 3.000", salary_range: "R$ 1.500 - R$ 12.000", education_time: "2-3 anos", education_level: "Tecnólogo", skills: ["Composição", "Iluminação", "Edição", "Criatividade", "Equipamentos"], market: "Eventos, e-commerce e conteúdo", growth_trend: "Crescente", entry_difficulty: "Baixa", remote_possible: true, international_possible: true, routine: "Ensaios e edição digital" },
  { title: "Cinema e Audiovisual", area: "Artes", subarea: "Audiovisual", description: "Cria filmes, vídeos e produções audiovisuais.", average_salary: "R$ 5.000", salary_range: "R$ 2.500 - R$ 20.000", education_time: "3-4 anos", education_level: "Tecnólogo", skills: ["Roteiro", "Direção", "Edição", "Criatividade", "Trabalho em Equipe"], market: "Streaming e conteúdo em alta", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Set de filmagem e edição" },
  { title: "Design de Interiores", area: "Artes", subarea: "Design de Espaços", description: "Decora e planeja espaços internos com funcionalidade e beleza.", average_salary: "R$ 4.500", salary_range: "R$ 2.500 - R$ 15.000", education_time: "2-3 anos", education_level: "Tecnólogo", skills: ["Criatividade", "Visão Espacial", "AutoCAD", "Paletas", "Organização"], market: "Imobiliário e residencial", growth_trend: "Crescente", entry_difficulty: "Baixa", remote_possible: true, international_possible: true, routine: "Projetos e visitas a clientes" },
  { title: "Moda", area: "Artes", subarea: "Design de Vestuário", description: "Cria coleções e peças de vestuário.", average_salary: "R$ 3.500", salary_range: "R$ 2.000 - R$ 15.000", education_time: "3-4 anos", education_level: "Tecnólogo", skills: ["Criatividade", "Costura", "Tendências", "Desenho", "Estilo"], market: "Varejo e marcas próprias", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Atelier e coleções" },
  { title: "Ilustração", area: "Artes", subarea: "Arte Digital", description: "Cria ilustrações para livros, produtos e mídias.", average_salary: "R$ 3.000", salary_range: "R$ 1.500 - R$ 12.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["Desenho", "Criatividade", "Procreate", "Digital Art", "Cor"], market: "Editorial e conteúdo digital", growth_trend: "Crescente", entry_difficulty: "Baixa", remote_possible: true, international_possible: true, routine: "Atelier digital e freelancer" },
  { title: "Direção de Arte", area: "Artes", subarea: "Comunicação Visual", description: "Conceitua e supervisiona a arte de campanhas e produções.", average_salary: "R$ 6.500", salary_range: "R$ 3.500 - R$ 20.000", education_time: "4 anos", education_level: "Superior", skills: ["Liderança", "Criatividade", "Visão Estética", "Comunicação", "Gestão"], market: "Agências e produtoras", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Concepção e direção de equipes" },
  { title: "Escultura", area: "Artes", subarea: "Arte Plástica", description: "Cria obras tridimensionais em diversos materiais.", average_salary: "R$ 2.800", salary_range: "R$ 1.500 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Modelagem", "Criatividade", "Técnicas Manuais", "Sensibilidade", "Paciência"], market: "Galerias e encomendas", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Atelier e exposições" },

  // ===== DESENVOLVIMENTO DE SISTEMAS =====
  { title: "Desenvolvedor Full Stack", area: "Desenvolvimento de Sistemas", subarea: "Web", description: "Desenvolve front-end e back-end de aplicações web.", average_salary: "R$ 8.000", salary_range: "R$ 4.000 - R$ 20.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["JavaScript", "React", "Node.js", "Banco de Dados", "APIs"], market: "Demanda altíssima globalmente", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Codificação e reuniões remotas" },
  { title: "Cientista de Dados", area: "Desenvolvimento de Sistemas", subarea: "Dados", description: "Analisa grandes volumes de dados para gerar insights.", average_salary: "R$ 12.000", salary_range: "R$ 6.000 - R$ 30.000", education_time: "4-5 anos", education_level: "Superior", skills: ["Python", "Machine Learning", "Estatística", "SQL", "Visualização"], market: "Uma das profissões mais valorizadas", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Modelagem e análise de dados" },
  { title: "DevOps", area: "Desenvolvimento de Sistemas", subarea: "Infraestrutura", description: "Integra desenvolvimento e operações para entregas contínuas.", average_salary: "R$ 10.000", salary_range: "R$ 5.000 - R$ 25.000", education_time: "4 anos", education_level: "Superior", skills: ["Linux", "Docker", "Kubernetes", "CI/CD", "Cloud"], market: "Crescente com nuvem e automação", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Automação e monitoramento" },
  { title: "Segurança da Informação", area: "Desenvolvimento de Sistemas", subarea: "Cybersecurity", description: "Protege sistemas e dados contra ataques cibernéticos.", average_salary: "R$ 9.000", salary_range: "R$ 5.000 - R$ 25.000", education_time: "4 anos", education_level: "Superior", skills: ["Redes", "Criptografia", "Análise", "Linux", "Forense"], market: "Crítico e em alta demanda", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Monitoramento e auditoria" },
  { title: "UX/UI Designer", area: "Desenvolvimento de Sistemas", subarea: "Design Digital", description: "Cria experiências e interfaces intuitivas.", average_salary: "R$ 6.000", salary_range: "R$ 3.000 - R$ 18.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["Figma", "Pesquisa UX", "Empatia", "Prototipação", "Criatividade"], market: "Essencial em produtos digitais", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Pesquisa, protótipos e testes" },
  { title: "Analista de Sistemas", area: "Desenvolvimento de Sistemas", subarea: "TI", description: "Levanta requisitos e projeta soluções de TI.", average_salary: "R$ 7.000", salary_range: "R$ 4.000 - R$ 18.000", education_time: "4 anos", education_level: "Superior", skills: ["Análise", "Comunicação", "Banco de Dados", "Gestão", "Lógica"], market: "Demanda em empresas de todos os portes", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Reuniões e documentação técnica" },
  { title: "Administrador de Banco de Dados", area: "Desenvolvimento de Sistemas", subarea: "Dados", description: "Gerencia e otimiza bancos de dados.", average_salary: "R$ 7.500", salary_range: "R$ 4.000 - R$ 18.000", education_time: "4 anos", education_level: "Superior", skills: ["SQL", "NoSQL", "Otimização", "Backup", "Linux"], market: "Estável e essencial em TI", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Manutenção e otimização" },
  { title: "Engenheiro de IA", area: "Desenvolvimento de Sistemas", subarea: "Inteligência Artificial", description: "Desenvolve modelos de inteligência artificial.", average_salary: "R$ 14.000", salary_range: "R$ 7.000 - R$ 35.000", education_time: "5 anos", education_level: "Superior", skills: ["Machine Learning", "Python", "Redes Neurais", "Matemática", "Deep Learning"], market: "Profissão emergente e muito valorizada", growth_trend: "Crescente", entry_difficulty: "Alta", remote_possible: true, international_possible: true, routine: "Treinamento e deploy de modelos" },
  { title: "Mobile Developer", area: "Desenvolvimento de Sistemas", subarea: "Mobile", description: "Cria aplicativos para iOS e Android.", average_salary: "R$ 8.000", salary_range: "R$ 4.000 - R$ 20.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["React Native", "Swift", "Kotlin", "APIs", "UI Mobile"], market: "Apps em constante crescimento", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Desenvolvimento e testes mobile" },
  { title: "Game Developer", area: "Desenvolvimento de Sistemas", subarea: "Games", description: "Programa jogos e experiências interativas.", average_salary: "R$ 7.000", salary_range: "R$ 3.500 - R$ 20.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["Unity", "C#", "Física", "Criatividade", "Lógica"], market: "Indústria de games em expansão", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Programação e iteração criativa" },

  // ===== MÚSICA =====
  { title: "Composição Musical", area: "Música", subarea: "Criação", description: "Cria obras musicais originais para diversos fins.", average_salary: "R$ 3.500", salary_range: "R$ 1.500 - R$ 15.000", education_time: "4 anos", education_level: "Superior", skills: ["Teoria Musical", "Criatividade", "Harmonia", "Instrumento", "Produção"], market: "Mídia, publicidade e streaming", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Estúdio e criação" },
  { title: "Produção Musical", area: "Música", subarea: "Estúdio", description: "Grava, mixa e masteriza faixas musicais.", average_salary: "R$ 4.000", salary_range: "R$ 2.000 - R$ 15.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["DAW", "Mixagem", "Masterização", "Áudio", "Criatividade"], market: "Streaming e conteúdo digital", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Estúdio e edição de áudio" },
  { title: "Educação Musical", area: "Música", subarea: "Ensino", description: "Ensina música em escolas e particulares.", average_salary: "R$ 3.000", salary_range: "R$ 2.000 - R$ 8.000", education_time: "4 anos", education_level: "Superior", skills: ["Didática", "Instrumento", "Paciência", "Teoria", "Comunicação"], market: "Escolas e aulas particulares", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Aulas e planejamento" },
  { title: "Regência", area: "Música", subarea: "Maestro", description: "Rege orquestras e corais.", average_salary: "R$ 5.000", salary_range: "R$ 2.500 - R$ 20.000", education_time: "4-5 anos", education_level: "Superior", skills: ["Leitura de Partitura", "Liderança", "Comunicação", "Ouvido", "Expressão"], market: "Orquestras e eventos", growth_trend: "Estável", entry_difficulty: "Alta", remote_possible: false, international_possible: true, routine: "Ensaios e apresentações" },
  { title: "Sound Design", area: "Música", subarea: "Áudio para Mídia", description: "Cria efeitos sonoros e trilhas para mídia.", average_salary: "R$ 4.500", salary_range: "R$ 2.500 - R$ 15.000", education_time: "2-4 anos", education_level: "Tecnólogo", skills: ["Áudio", "DAW", "Criatividade", "Tecnologia", "Sensibilidade"], market: "Games, cinema e publicidade", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Estúdio e edição de som" },
  { title: "Técnico de Áudio", area: "Música", subarea: "Som ao Vivo", description: "Opera equipamentos de som em eventos e estúdios.", average_salary: "R$ 3.000", salary_range: "R$ 1.800 - R$ 10.000", education_time: "2 anos", education_level: "Técnico", skills: ["Equipamentos de Som", "Acústica", "Prática", "Resistência", "Organização"], market: "Eventos e estúdios", growth_trend: "Estável", entry_difficulty: "Baixa", remote_possible: false, international_possible: true, routine: "Montagem e operação ao vivo" },
  { title: "Musicoterapia", area: "Música", subarea: "Saúde", description: "Usa a música como recurso terapêutico.", average_salary: "R$ 3.500", salary_range: "R$ 2.000 - R$ 10.000", education_time: "4 anos", education_level: "Superior", skills: ["Empatia", "Música", "Terapia", "Comunicação", "Sensibilidade"], market: "Saúde e bem-estar", growth_trend: "Crescente", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Sessões terapêuticas" },
  { title: "Canto", area: "Música", subarea: "Performance", description: "Atua como cantor profissional em diversos estilos.", average_salary: "R$ 3.500", salary_range: "R$ 1.500 - R$ 20.000", education_time: "3-4 anos", education_level: "Tecnólogo", skills: ["Técnica Vocal", "Expressão", "Ouvido", "Performance", "Resistência"], market: "Shows, estúdio e eventos", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Ensaios e apresentações" },
  { title: "Instrumentista", area: "Música", subarea: "Performance", description: "Toca instrumentos profissionalmente.", average_salary: "R$ 3.500", salary_range: "R$ 1.500 - R$ 18.000", education_time: "3-4 anos", education_level: "Tecnólogo", skills: ["Técnica Instrumental", "Leitura", "Prática", "Performance", "Ouvido"], market: "Orquestras, bandas e estúdio", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: false, international_possible: true, routine: "Ensaios e apresentações" },
  { title: "Arranjo Musical", area: "Música", subarea: "Criação", description: "Cria arranjos para músicas e produções.", average_salary: "R$ 4.000", salary_range: "R$ 2.000 - R$ 15.000", education_time: "4 anos", education_level: "Superior", skills: ["Harmonia", "Teoria", "Orquestração", "Criatividade", "DAW"], market: "Estúdio e produções", growth_trend: "Estável", entry_difficulty: "Média", remote_possible: true, international_possible: true, routine: "Estúdio e criação" }
];